/* Auth Types */
export const ADD_NAME = 'ADD_NAME';
export const ADD_EMAIL = 'ADD_EMAIL';
export const ADD_PASSWORD = 'ADD_PASSWORD';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER';
export const FAILURE_REGISTER = 'FAILURE_REGISTER';
export const SIGN_IN_LOADING = 'SIGN_IN_LOADING';
export const SIGN_UP_LOADING = 'SIGN_UP_LOADING';

/* Application Types */
export const ADD_CONTACT = 'ADD_CONTACT';
export const ADD_NEW_CONTACT_ERROR = 'ADD_NEW_CONTACT_ERROR';
export const ADD_NEW_CONTACT_SUCCESS = 'ADD_NEW_CONTACT_SUCCESS';

export const CONTACTS_LIST = 'CONTACTS_LIST';
export const USER_CONTACT = 'USER_CONTACT';
export const ADD_CONTACT_CHAT = 'ADD_CONTACT_CHAT';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export const FETCH_ALL_CHATS = 'FETCH_ALL_CHATS';


export const LIST_CONVERSATION_USER = 'LIST_CONVERSATION_USER';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';

export const ADD_TEMPLATE = 'ADD_TEMPLATE';
export const ERROR_ADDING_TEMPLATE = 'ERROR_ADDING_TEMPLATE';

export const TEMPLATES_LIST = 'TEMPLATES_LIST';
export const QUESTION_LIST = 'QUESTION_LIST';

export const ADD_QUESTION = 'ADD_QUESTION';
export const ERROR_ADDING_QUESTION = 'ERROR_ADDING_QUESTION';

export const FEEDBACK_LIST = 'FEEDBACK_LIST';

export const USER_TEMPLATE_LIST = 'USER_TEMPLATE_LIST';

export const COACH_TEMPLATE_LIST = 'COACH_TEMPLATE_LIST';

export const SINGLE_TEMPLATE = 'SINGLE_TEMPLATE';

export const SPLASH_READ = 'SPLASH_READ';

export const CREATE_TEMPLATE = 'CREATE_TEMPLATE';

export const FETCH_SURVEY_QUESTION = 'FETCH_SURVEY_QUESTION';
export const FETCH_SURVEY_FEEDBACK = 'FETCH_SURVEY_FEEDBACK';
export const FETCH_QUESTION = 'FETCH_QUESTION';

export const SET_M_NUMBER = 'SET_M_NUMBER';
export const OTP_ERROR = "OTP_ERROR";
export const VERIFY_OTP = "VERIFY_OTP";